### ISSUE TITLE
[BUG] The elasticsearch addon takes the ES client as its own dependency, so any version skew with root breaks the addon build

### ISSUE THREAD

**Issue by jwilleke** [jwilleke/ngdpbase#1314]
## 🐛 Bug Description

`addons/elasticsearch` is its own npm root with its own lockfile, so it installs a **nested** copy of `@elastic/elasticsearch`. Core constructs the guarded client and passes it across the addon boundary:

```ts
// addons/elasticsearch/index.ts:109
const client = createGuardedElasticsearchClient(esUrl, readConfig);  // root's Client
provider = new Sist2AssetProvider(client, esIndex, ...);             // typed against the NESTED Client
```

`Client` is a class with private members, so it is compared nominally. Two identical versions emit identical declarations and it compiles — by coincidence, not by design. The moment the two roots resolve different versions, the addon build fails.

## 🔄 Steps to Reproduce

Bump one side only, which is the only thing Dependabot is able to propose:

```
cd addons/elasticsearch && npm install @elastic/elasticsearch@^8.19.2
npm run build
```

## ❌ Actual Behavior

```
index.ts(109,39): error TS2345: Argument of type
  node_modules/@elastic/elasticsearch/lib/client.default is not assignable to parameter of type
  addons/elasticsearch/node_modules/@elastic/elasticsearch/lib/client.default
```

This is exactly what happened to [#1287](https://github.com/jwilleke/ngdpbase/pull/1287), which sat red and could never have gone green on its own — Dependabot edits one `package.json` per PR and cannot express the change that works.

## ✅ Expected Behavior

A patch bump of the Elasticsearch client on either side does not break the addon build.

## 📝 Additional Context

Worked around in [2f976c0a](https://github.com/jwilleke/ngdpbase/commit/2f976c0a) by moving both sides to `^8.19.2` together. That unblocks today and fixes nothing: **the next elasticsearch patch release recreates it**, and each time it surfaces as a confusing type error rather than as the dependency-structure problem it is.

The durable fix is for the addon to declare the client as a `peerDependency` of the host rather than a `dependency` of its own — one copy, supplied by core, which is already how the value actually arrives at run time. The addon boundary is checked by `npm run lint:addons` (`scripts/check-addon-boundary.ts`, [#1192](https://github.com/jwilleke/ngdpbase/issues/1192)), so the guard for "an addon must not install its own copy of a type it receives from the host" plausibly belongs there too.

Worth checking whether any other bundled addon takes a host-supplied value typed from its own nested copy — the same shape would be latent there.

**Comment by jwilleke** [comment]
Fixed in [c4fbff3a](https://github.com/jwilleke/ngdpbase/commit/c4fbff3a) — `in-review`, not closed, so the call is yours.

The addon never needed the dependency. Every reference to it is type-only:

```
addons/elasticsearch/src/Sist2AssetProvider.ts:17
  import type { Client, estypes } from "@elastic/elasticsearch";
```

The only value import in the repository is core’s, in `src/http/guardedElasticsearch.ts:28`, where the client is constructed and egress-gated. So the addon’s actual requirement is "the host supplies this" — which is what a peer dependency says. `peerDependenciesMeta` marks it optional so npm does not reinstall the nested copy; `build:addons` runs `npm install` in that directory on every build, which is exactly where it would have come back.

Nested tree: **30 packages → 3**. apache-arrow, flatbuffers, hpagent, undici and the rest were all being installed a second time to satisfy types that are erased at compile. The addon’s `undici` override went with them — it pinned the transport’s undici, which only arrived through this dependency, and root resolves 6.28.0 on its own.

## Proof that it actually fixes the thing, not just today’s symptom

I bumped root to the 9.5.1 that [#1321](https://github.com/jwilleke/ngdpbase/pull/1321) proposes and rebuilt, then reverted. **The dual-package error is gone.** What appears instead is a genuine API incompatibility:

```
Before (the packaging accident):
  TS2345: Argument of type ".../@elastic/elasticsearch/lib/client".default
          is not assignable to parameter of type
          "addons/elasticsearch/node_modules/@elastic/elasticsearch/lib/client".default

After (an honest signal):
  src/Sist2AssetProvider.ts(270,38): TS2769: No overload matches this call.
    Type "SortCombinations[]" is not assignable to type "undefined"
```

That is the whole point of the change. The old error named the same package twice and told you nothing about your code; the new one says the ES 9 `search()` request shape moved and this addon’s query needs migrating. Skew is now impossible by construction — there is no addon-side version left to disagree with root.

The peer range is `^8.19.2` deliberately rather than something looser: the addon reads `estypes`, whose shape tracks the client major, so a root moving to 9.x should surface as a visible peer mismatch to be judged rather than pass silently.

## Verified

- addon typecheck clean against root’s single copy
- `npm run build` including `build:addons` — the reinstall did not resurrect the nested copy
- `npm run lint:addons` clean
- suite 9153 passed / 10 skipped across 444 files
- jimstest restarted: addon discovered, enabled, in the load order, and reaching `[AssetManager] Registered provider "sist2"` with no `ERR_MODULE_NOT_FOUND`

The runtime check matters here specifically — the defect this area already shipped once (v4.13.0, per the docstring in `scripts/check-addon-boundary.ts`) was green in every test while the addon was dead in the container.

## Not done

I did not audit the other bundled addons for the same shape, which this issue also asked for. `forms`, `calendar` and `journal` declare `express` and `uuid`; express’s types are structural interfaces rather than classes with private members, so they do not have the nominal-comparison problem `Client` has, and `uuid` is genuinely their own runtime value. That is reasoning, not a check — worth a pass of its own before this is closed.

**Comment by jwilleke** [comment]
The audit this issue asked for is done — the part I had flagged as reasoned-but-unchecked. **It comes back clean: the nominal hazard exists nowhere else.**

Tested rather than argued, since inspection was exactly what I said was insufficient last time.

## The hazard needs two things at once

A nested copy of the package, **and** a type that TypeScript compares *nominally* — a class with private or protected members. Structural types unify across duplicate copies; nominal ones do not. `Client` qualified. Nothing else does.

| package | nested copy? | boundary type | nominal? | verdict |
|---|---|---|---|---|
| `@elastic/elasticsearch` | was yes | `Client` | **class, private members** | the bug — fixed in [c4fbff3a](https://github.com/jwilleke/ngdpbase/commit/c4fbff3a) |
| `express` | yes, ×4 addons | `Application`, `Request`, `Response`, `Router` | **no — all `interface`, 0 private/protected** | safe |
| `winston` | **no** — single copy at root | `Logger` | class (would be nominal) | safe, because there is only one copy |
| `zod` | yes (forms, 3.x vs root 4.x) | — | — | never crosses the boundary; core imports zod nowhere |
| `uuid`, `date-fns`, `ts-ics`, `fast-xml-parser` | yes | — | — | addon-owned values, not host-supplied |

## The empirical check

Reasoning that express interfaces are structural is still just reasoning, so I forced the failure case: `addons/calendar` pinned to express **5.1.0** against root **5.2.1**, then typechecked.

```
calendar typecheck under express SKEW (5.1.0 vs root 5.2.1) exit=0
```

Clean. Reverted afterwards; nothing committed. That is the same experiment that made ES 9.5.1 produce a real error instead of a packaging one, run against the case I had only asserted was fine.

Two near-misses worth recording, because both would flip if someone changed one line:

- **`winston` is safe by accident, not by design.** `Logger` is `class Logger extends NodeJSStream.Transform` — genuinely nominal. `calendar` does `import type { Logger } from "winston"` while declaring no winston dependency, so it resolves up to root’s single copy and unifies. The day an addon adds `winston` to its own `package.json`, this issue comes back with a different package name on it.
- **`zod` is already skewed 3.25.76 against root 4.2.1** and it does not matter only because core imports zod nowhere at all.

## Also found

- `forms`, `calendar`, `journal`, `feeds` each duplicate ~70 packages from root via their express declaration, with seven already drifted. Not this bug, real all the same — filed separately as [#1324](https://github.com/jwilleke/ngdpbase/issues/1324) rather than widened into here.
- The generator (`scripts/create-addon.ts`) and the `hello-ngdp` template addon both emit `dependencies: {}` already, so **the wrong shape is not being propagated to new addons**. That was the outcome I most wanted to rule out.
- `geohazardwatch`’s addon manifest declares `express` as a runtime dependency — same lesser shape, noted in [#1324](https://github.com/jwilleke/ngdpbase/issues/1324).

Nothing here changes the fix or its verification. This issue is still `in-review` for you to close.

**Comment by jwilleke** [comment]
Closed by the operator after review (2026-09-12).
